export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const GET_COURSES = "GET_COURSES";
export const GET_SINGLE_COURSE = "GET_SINGLE_COURSE";
export const GET_CATEGORIES = "GET_CATEGORIES";
